import Title from 'components/TitleSection'
import s from './Homosa.module.sass'

type Props = {}

export default function Homosa (props: Props) {
    return(
        <section>
            <div className={`${s.container_homosa} homo-container`}>
                <div className={s.heading}>
                    <Title statusText={false} title='Homosa' />
                    <div className={s.demo_version}>
                        <img src="/assets/Homosa/ic_video.svg" alt="" />
                        <p>DEMO VERSION</p>
                    </div>
                </div>

                <div className={s.content_homosa}>
                    <div className={`${s.blockContent} ${s.blockContentLeft}`}>
                        <h1>Why homosa ?</h1>
                        <p>Proceeds from Public Sales are used to quickly build an NFTs Market Place social network called HOMOSA. We are Homosapience</p>
                        <p> HOMOSA social network will be a livelihood, generating income for war victims who have lost their jobs and regular sources of income</p>
                    </div>
                    <div className={s.im_noWar}><img src="/assets/Homosa/im_noWar.png" alt="" /></div>
                    <div className={`${s.blockContent} ${s.blockContentRight}`}>
                        <h1>How does it works?</h1>
                        <p>Income is generated by drawing, capturing life scenes, moments of War and Peace, using blockchain tools, simple operations, automatically generating random genealogical art paintings. Below is the monetization model for End Users that has worked. Now the process of generating random genealogical NFTs art is personalized, simplified into profile features</p>
                    </div>
                </div>
            </div>


            <div className={`${s.container_HomoTokennomics} homo-container`}>
                <div className={s.im_vector}><img src="/assets/Homosa/im_vectorHomosa.png" alt="" /></div>

                <div className={s.heading_HomoTokennomics}>
                    <Title statusText={false} title='Homo Tokennomics' />
                    <p>If you are a supporter of the Ukrainian people, war victims. Come and buy HOMO token now. Your act of buying tokens will help form the token value that Ukrainians have received the Airdrop</p>
                    <a href="#" className={s.btn_wp}>White paper</a>
                </div>


                <div className={s.content_chart}>
                    <img src="/assets/Homosa/im_chart.png" alt="" />
                    <div className={s.details_chart}>
                        <div className={s.item}>
                            <div className={s.bg_chart}></div>
                            <p>51%<span>: Airdrop Ukraine, DAO voting</span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart2}`}></div>
                            <p>4%<span>: Global marketing </span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart3}`}></div>
                            <p>9%<span>: Airdrop for war victim, DAO voting</span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart4}`}></div>
                            <p>5%<span>: Global team + Sponsors + Advisors + Incubator </span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart5}`}></div>
                            <p>20%<span>: Public sales IEO, IDO, ICO, DAO voting</span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart6}`}></div>
                            <p>1%<span>: Private sales</span></p>
                        </div>
                        <div className={s.item}>
                            <div className={`${s.bg_chart} ${s.bg_chart7}`}></div>
                            <p>10%<span>: Staking, Farming</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}